import type { Metadata } from 'next'
import './globals.css'

import localFont from 'next/font/local'

const heleveticaNeue = localFont({src : "./font/Light.woff"})

export const metadata: Metadata = {
  title: 'Eurecah | Creative Agency',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={heleveticaNeue.className}>
        {children}
      </body>
    </html>
  )
}
